//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prime_Legal.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public Nullable<int> IdTypeDeal { get; set; }
        public Nullable<int> IdState { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual State State { get; set; }
        public virtual TypeDeal TypeDeal { get; set; }
    }
}
